name: memory_ticket_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  get_it: ^9.2.1
  path_provider: ^2.1.6
#  image_picker: ^1.2.3
#  camera: ^0.12.0+2
  permission_handler: ^12.0.3
  intl: ^0.20.3
  uuid: ^4.6.0
#  share_plus: ^13.2.1
  google_fonts: ^8.2.0
  flutter_svg: ^2.3.0
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#4D41DF"
  image: assets/app_icon.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  
  android_12:
    image: assets/app_icon.png
    icon_background_color: "#4D41DF"
  
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4D41DF"
  adaptive_icon_foreground: "assets/app_icon.png"

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
